### ISSUE TITLE
HDF5 error / Unable to open train_data_processed.h5

### ISSUE THREAD

**Issue by AmethystZeroAtwell** [pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#5]
Hello,when I run combi_models an error occur
here is the error messages
Traceback (most recent call last):
  File "d:\RCB\Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN-master\combi_models.py", line 47, in <module>
    train_data = pd.read_hdf(os.path.join(root_dir,'data','train_data_processed.h5'),'table')
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 389, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 740, in select
    return it.get_result()
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 1518, in get_result
    results = self.func(self.start, self.stop, where)
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 733, in func
    columns=columns)
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 2995, in read
    start=_start, stop=_stop)
  File "D:\ANACONDA\lib\site-packages\pandas\io\pytables.py", line 2540, in read_array
    ret = node[0][start:stop]
  File "D:\ANACONDA\lib\site-packages\tables\vlarray.py", line 681, in __getitem__
    return self.read(start, stop, step)[0]
  File "D:\ANACONDA\lib\site-packages\tables\vlarray.py", line 821, in read
    listarr = self._read_array(start, stop, step)
  File "tables\hdf5extension.pyx", line 2155, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array

Thank you in advance.

**Comment by pavitrakumar78** [comment]
Hi,

Please check this thread: https://github.com/pandas-dev/pandas/issues/24839  

This seems to be something very recent. Let me know if downgrading solves the problem.

**Comment by AmethystZeroAtwell** [comment]
I run `conda install numpy==1.15.4` and solve the problem successfully.Thank you so much!
